#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=16GB
#SBATCH --partition=gpu
#SBATCH --gres=gpu:v100:2
#SBATCH --time=1:00:00
#SBATCH --account=xiangren_818

module purge
eval "$(conda shell.bash hook)"

conda activate /home1/dpwani/.conda/envs/dipak-vqa-2
python test.py --saved_model='/scratch2/dpwani/dataset/models/mobilenet/best_model.pt' --image_path="/scratch2/dpwani/dataset/resized_images/val2014/COCO_val2014_000000536235.jpg" --question="which animal is it"
